### ISSUE TITLE
Setting up Kipoi using Singularity

### ISSUE THREAD

**Issue by IshikaLuthra** [kipoi/kipoi#601] opened 2021-07-26 18:10 UTC
Hi,  

I am trying to set up Kipoi (specifically BPNET-OSKN) using Singularity on Compute Canada. I first do `load module load singularity/3.7` Then I try: `singularity pull haimasree/kipoi-docker:bpnet-oskn`.

Unfortunately, I am getting an error. `FATAL:   While pulling library image: error fetching image: image does not exist in the library: haimasree/kipoi-docker:bpnet-oskn (amd64)`

Is there a way to correct this?

Thank you for you help :)

Ishika

**Comment by haimasree** [comment] 2021-07-26 19:41
Hi Ishika, can you try the following?
```
singularity pull docker://haimasree/kipoi-docker:bpnet-oskn
```

**Comment by haimasree** [comment] 2021-07-26 19:52
Also as a sanity check, may I suggest the following?
```
singularity exec kipoi-docker_bpnet-oskn.sif kipoi test BPNet-OSKN --source=kipoi
```

If the above runs without any error then kipoi-docker_bpnet-oskn.sif is ready to use :)

**Comment by IshikaLuthra** [comment] 2021-07-26 21:25
Hi, Unfortunately I am still getting errors :( 

`INFO:    Converting OCI blobs to SIF format
WARNING: 'nodev' mount option set on /scratch, it could be a source of failure during build process
FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: unable to create new build: while ensuring correct compression algorithm: while creating squashfs: create command failed: exit status 1: FATAL ERROR:Failed to create thread`

**Comment by IshikaLuthra** [comment] 2021-07-27 04:20
I have also been trying to follow this tutorial: https://ngc.nvidia.com/catalog/containers/hpc:kipoi but it also seems to be giving me errors.

**Comment by haimasree** [comment] 2021-07-27 09:17
Hi Ishika, I verified again and cannot reproduce your error on the hpc cluster I have access to. It is a lsf cluster with singularity 3.5 installed in it. I have a few thoughts. Here they are -
1. My best guess is your hpc environment is causing trouble. If you have limited RAM (via ulimit or similar), or you have a lot of cores without large amounts of RAM, then the default behavior of squashfs which Singularity calls to create SIF images can exhaust memory. Reference: https://github.com/hpcng/singularity/issues/5469 and https://github.com/hpcng/singularity/issues/5434. 
2. If you are new to singularity it would be great if you can check what size of containers you can actually run in your setup.  I dont know how much memory singularity pull used in my case but the final .sif image was of size 3.6 GB. If you see you can handle a similar size image see if pulling from dockerhub is the main problem as opposed to singularity hub or any local registry your institution may have. Without knowing much about your unique setup it is rather hard for me to weigh in. Perhaps you can open an issue on the singulairty github repo referred to above? You can also ask your sys admin about this. 
3. You can also try to build the singularity image from scratch. Follow this template -  https://github.com/kipoi/kipoi/blob/master/envs/Singularity. I would swap out https://github.com/kipoi/kipoi/blob/master/envs/Singularity#L35 for ```kipoi env create BPNet-OSKN``` otherwise you would have a massive image and will take quite a while longer to run.
4. Finally, since I already craeted the .sif file and tested it as mentioned above, the easiest would be for me to share the image with you. Unfortunately, I need more information from Ziga about this and will not know before next week. I will write back once I know more.

**Comment by haimasree** [comment] 2021-07-27 09:23
> I have also been trying to follow this tutorial: https://ngc.nvidia.com/catalog/containers/hpc:kipoi but it also seems to be giving me errors.

Do you mean you tried to run the following ?
```
 singularity build kipoi_v0.6.8-keras2.simg docker://nvcr.io/hpc/kipoi:v0.6.8-keras2
singularity run --nv -B $(pwd):/host_pwd kipoi:v0.6.8_keras2.simg /bin/bash -c "source activate kipoi-py3-keras2 kipoi get-example DeepSEA/predict -o /host_pwd/example"
```

This is not different from the instructions I wrote above. It is also creating a singularity image from its docker counterpart and running some kind of kipoi cli on it. If the above did not work I would not expect this to work either. May I suggest you start with understanding what type/size of images your setup can actually work with and reach out to your sys admin or singularity github repo to get solutions tailored to your unique need.

**Comment by IshikaLuthra** [comment] 2021-07-27 22:26
Hi, 

Thank you for all your help! I really appreciate it. It seem that the cluster I was using makes it really difficult to use Conda. I switched over to another cluster with Conda permissions and I was able to run Kipoi successfully quite easily :)

Thank you,

Ishika

**Comment by haimasree** [comment] 2021-07-28 08:58
Great to hear that. No worries at all. I will close this issue and the other one. Feel free to open another issue if you need further help.

**Closed by haimasree** 2021-07-28 08:58 UTC
